import { modules, allInterviewQuestions } from './modules.js'

const STORAGE_KEY='moth-academy-state-v1'
const initialState={completedModules:[],practiceAnswers:{},interviewAnswers:{},lastModule:1}
let state=loadState(), view='home', activeModule=state.lastModule||1, interviewFilter='all', interviewIndex=0, revealAnswer=false, mobileOpen=false

function loadState(){try{return {...initialState,...JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}}catch{return {...initialState}}}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));renderProgress();flash('Guardado')}
function flash(text){const t=document.getElementById('toast');if(!t)return;t.textContent=text;t.classList.add('show');clearTimeout(flash.timer);flash.timer=setTimeout(()=>t.classList.remove('show'),1300)}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function icon(x){return `<span class="svg-icon" aria-hidden="true">${x}</span>`}
function go(v){view=v;mobileOpen=false;render();window.scrollTo({top:0,behavior:'smooth'})}
function openModule(id){activeModule=id;state.lastModule=id;saveState();go('module')}
function toggleComplete(id){state.completedModules=state.completedModules.includes(id)?state.completedModules.filter(x=>x!==id):[...state.completedModules,id];saveState();render()}
function setPractice(moduleId,idx,value){state.practiceAnswers[`${moduleId}-${idx}`]=value;saveStateDebounced()}
function setInterview(id,value){state.interviewAnswers[id]=value;saveStateDebounced()}
let saveTimer;function saveStateDebounced(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));renderProgress();flash('Respuesta guardada')},400)}
function progress(){return Math.round(state.completedModules.length/modules.length*100)}
function renderProgress(){document.querySelectorAll('[data-progress-pct]').forEach(el=>el.textContent=`${progress()}%`);document.querySelectorAll('[data-progress-bar]').forEach(el=>el.style.width=`${progress()}%`)}

function shell(content){return `
<div class="app-shell">
  <div class="sidebar-backdrop ${mobileOpen?'show':''}" data-action="close-menu"></div>
  <aside class="sidebar ${mobileOpen?'open':''}">
    <button class="sidebar-close icon-btn" data-action="close-menu">✕</button>
    <button class="brand" data-go="home"><img src="./assets/moth-logo.png" alt="Logo de Moth Academy"><div><span>MOTH</span><strong>ACADEMY</strong><small>QA Study & Practice</small></div></button>
    <nav>
      ${navButton('home','⌂','Inicio')}${navButton('modules','▤','Módulos')}${navButton('practice','✎','Prácticas')}${navButton('interview','◎','Modo entrevista')}${navButton('journal','◉','Mi bitácora')}${navButton('resources','▣','Recursos')}
    </nav>
    <div class="sidebar-bottom">
      <div class="mini-progress"><div><span>Tu progreso</span><strong data-progress-pct>${progress()}%</strong></div><div class="progress-track"><i data-progress-bar style="width:${progress()}%"></i></div></div>
      <div class="data-actions"><button data-action="export">⇩ Exportar progreso</button><label>⇧ Importar progreso<input id="import-progress" type="file" accept="application/json"></label><button class="danger-ghost" data-action="reset">↻ Reiniciar</button></div>
      <p class="storage-note">Tus respuestas se guardan sólo en este navegador. Podés exportarlas para llevarlas a otro dispositivo.</p>
    </div>
  </aside>
  <main class="static-main">
    <header class="mobile-header"><button class="icon-btn" data-action="open-menu">☰</button><div class="mobile-brand"><img src="./assets/moth-logo.png" alt=""><strong>Moth Academy</strong></div></header>
    ${content}
  </main>
</div>`}
function navButton(id,i,label){return `<button class="${view===id?'active':''}" data-go="${id}">${icon(i)}<span>${label}</span></button>`}
function pageTitle(kicker,title,subtitle){return `<header class="page-title"><span class="label">${kicker}</span><h1>${title}</h1><p>${subtitle}</p></header>`}
function moduleCard(m,compact=false){const done=state.completedModules.includes(m.id);return `<button class="module-card ${done?'done':''}" data-module="${m.id}"><div class="module-number">${String(m.id).padStart(2,'0')}</div><div class="module-card-copy"><span>${esc(m.accent)}</span><h3>${esc(m.title)}</h3><p>${esc(m.short)}</p></div><div class="module-status">${done?'✓ Repasado':'› Abrir'}</div></button>`}

function home(){const next=modules.find(m=>!state.completedModules.includes(m.id))||modules.at(-1);const answerCount=Object.values(state.practiceAnswers).filter(x=>x?.trim()).length;const intCount=Object.values(state.interviewAnswers).filter(x=>x?.trim()).length;return `<div class="page home-page">
<section class="hero"><div class="hero-copy"><span class="eyebrow">✦ Aprender · Practicar · Evolucionar</span><h1>Tu compañero de entrenamiento <em>QA</em>.</h1><p>Repasá conceptos, practicá criterio y prepará entrevistas sin notas, sin login y sin ruido. Lo importante no es memorizar: es poder explicar qué harías y por qué.</p><div class="hero-actions"><button class="primary" data-module="${next.id}">Continuar con Módulo ${next.id} ›</button><button class="secondary" data-go="interview">Practicar entrevista ◎</button></div></div><div class="hero-mark"><img src="./assets/moth-logo.png" alt="Moth Academy"></div></section>
<section class="dashboard-grid"><div class="progress-card large"><div class="card-top"><div><span class="label">RECORRIDO</span><h2>${state.completedModules.length} de 9 módulos repasados</h2></div><strong class="big-number" data-progress-pct>${progress()}%</strong></div><div class="progress-track big"><i data-progress-bar style="width:${progress()}%"></i></div><div class="stat-row"><span>✓ ${state.completedModules.length} módulos</span><span>✎ ${answerCount} prácticas respondidas</span><span>◎ ${intCount} respuestas de entrevista</span></div></div><button class="quick-card" data-go="journal">${icon('◉')}<span>Mi bitácora</span><small>Volvé a leer lo que respondiste.</small>${icon('›')}</button><button class="quick-card" data-go="resources">${icon('▣')}<span>Recursos</span><small>Workbook y herramientas recomendadas.</small>${icon('›')}</button></section>
<section class="section-block"><div class="section-heading"><div><span class="label">MÓDULOS</span><h2>Elegí dónde querés repasar</h2></div><button class="text-link" data-go="modules">Ver todos ›</button></div><div class="module-grid compact">${modules.slice(0,6).map(moduleCard).join('')}</div></section>
</div>`}
function modulesView(){return `<div class="page">${pageTitle('RECORRIDO','Módulos de estudio','Nueve módulos para repasar conceptos, practicar y aprender a explicarlos profesionalmente.')}<div class="search-box">⌕ <input id="module-search" placeholder="Buscar módulo o tema..."></div><div id="module-grid" class="module-grid">${modules.map(moduleCard).join('')}</div></div>`}
function moduleView(){const m=modules.find(x=>x.id===activeModule);const done=state.completedModules.includes(m.id);return `<div class="page module-page"><div class="module-hero"><div><span class="label">MÓDULO ${String(m.id).padStart(2,'0')} · ${esc(m.accent.toUpperCase())}</span><h1>${esc(m.title)}</h1><p>${esc(m.short)}</p></div><button class="complete-btn ${done?'done':''}" data-action="complete" data-id="${m.id}">${done?'✓ Repasado':'Marcar como repasado'}</button></div><div class="reading-layout"><article class="lesson">${m.sections.map(sectionHTML).join('')}${practicePanel(m)}${interviewPanel(m)}</article></div><div class="module-nav">${m.id>1?`<button data-module="${m.id-1}">‹ Módulo ${m.id-1}</button>`:'<span></span>'}${m.id<modules.length?`<button data-module="${m.id+1}">Módulo ${m.id+1} ›</button>`:`<button data-module="1">Volver al inicio ↻</button>`}</div></div>`}
function sectionHTML(s){return `<section class="lesson-section"><h2>${esc(s.title)}</h2>${s.body?`<p>${esc(s.body)}</p>`:''}${s.bullets?`<ul>${s.bullets.map(b=>`<li>${esc(b)}</li>`).join('')}</ul>`:''}${s.code?`<pre><code>${esc(s.code)}</code></pre>`:''}</section>`}
function practicePanel(m){return `<section class="practice-panel"><span class="panel-kicker">✎ PRÁCTICA</span><h2>Probalo vos</h2>${m.practices.map((p,idx)=>practiceItem(m,idx,p)).join('')}</section>`}
function practiceItem(m,idx,p){const key=`${m.id}-${idx}`, val=state.practiceAnswers[key]||'';return `<div class="practice-item"><p><strong>${idx+1}.</strong> ${esc(p)}</p><textarea data-practice="${key}" placeholder="Escribí tu respuesta. Se guarda automáticamente en este navegador.">${esc(val)}</textarea><small class="${val?'save-indicator':''}">${val?'Respuesta guardada.':'Todavía sin respuesta.'}</small></div>`}
function interviewPanel(m){return `<section class="interview-panel"><span class="panel-kicker">◎ TE PUEDEN PREGUNTAR</span><h2>Preguntas de entrevista</h2>${m.interview.map((x,idx)=>`<div class="qa-row"><button data-disclosure="${m.id}-${idx}"><span>${esc(x.q)}</span><span>›</span></button><p id="disc-${m.id}-${idx}" class="hidden">${esc(x.a)}</p></div>`).join('')}</section>`}
function practiceView(){return `<div class="page">${pageTitle('PRÁCTICA','Pensar antes de responder','No hay puntaje. Escribí tu criterio y volvé más adelante para comparar cómo evolucionó tu respuesta.')}<div class="practice-list">${modules.map(m=>`<section class="practice-module"><div class="practice-module-head"><div><span>MÓDULO ${m.id}</span><h2>${esc(m.title)}</h2></div><button class="text-link" data-module="${m.id}">Abrir módulo ›</button></div>${m.practices.map((p,idx)=>practiceItem(m,idx,p)).join('')}</section>`).join('')}</div></div>`}
function interviewView(){const list=interviewFilter==='all'?allInterviewQuestions:allInterviewQuestions.filter(q=>q.moduleId===Number(interviewFilter));if(interviewIndex>=list.length)interviewIndex=0;const q=list[interviewIndex];const val=state.interviewAnswers[q.id]||'';return `<div class="page">${pageTitle('MODO ENTREVISTA','Respondé antes de revelar','Entrená una respuesta natural. La guía sirve para comparar ideas, no para memorizar palabra por palabra.')}<div class="interview-toolbar"><label>Filtrar por módulo<select id="interview-filter"><option value="all">Todos los módulos</option>${modules.map(m=>`<option value="${m.id}" ${String(interviewFilter)===String(m.id)?'selected':''}>Módulo ${m.id} · ${esc(m.title)}</option>`).join('')}</select></label><button class="secondary" data-action="random">✦ Pregunta aleatoria</button></div><section class="interview-card"><div class="interview-meta"><span>Módulo ${q.moduleId}</span><span>${esc(q.moduleTitle)}</span></div><h2>${esc(q.q)}</h2><textarea data-interview="${q.id}" placeholder="Respondé con tus palabras antes de mirar la guía.">${esc(val)}</textarea><div class="interview-actions"><button class="primary" data-action="reveal">${revealAnswer?'Ocultar guía':'Ver respuesta guía'}</button><button class="secondary" data-action="next-question">Otra pregunta ›</button></div>${revealAnswer?`<div class="answer-guide"><span>RESPUESTA GUÍA</span><p>${esc(q.a)}</p></div>`:''}</section></div>`}
function journalView(){const p=modules.flatMap(m=>m.practices.map((prompt,idx)=>({type:'PRÁCTICA',module:m,prompt,answer:state.practiceAnswers[`${m.id}-${idx}`]}))).filter(x=>x.answer?.trim());const iq=allInterviewQuestions.map(q=>({type:'ENTREVISTA',module:modules.find(m=>m.id===q.moduleId),prompt:q.q,answer:state.interviewAnswers[q.id]})).filter(x=>x.answer?.trim());const entries=[...p,...iq];return `<div class="page">${pageTitle('MI BITÁCORA','Tus respuestas, guardadas','Todo queda en este navegador para que puedas volver, releer y responder de nuevo cuando quieras.')}${entries.length?`<div class="journal-list">${entries.map(e=>`<article class="journal-entry"><div class="journal-tag">${e.type} · MÓDULO ${e.module.id}</div><h3>${esc(e.prompt)}</h3><p>${esc(e.answer)}</p><button class="text-link" data-module="${e.module.id}">Repasar ${esc(e.module.title)} ›</button></article>`).join('')}</div>`:`<div class="empty-state">◉<h2>Tu bitácora todavía está en blanco</h2><p>Respondé una práctica o una pregunta de entrevista y aparecerá acá automáticamente.</p></div>`}</div>`}
function resourcesView(){const rs=[['▤','QA Practical Workbook 2026','Documento maestro de Moth Academy.','./resources/Moth_Academy_QA_Practical_Workbook_2026.docx',true],['↗','OpenCart Demo by Abstracta','Laboratorio principal para prácticas funcionales.','https://opencart.abstracta.us/'],['↗','Postman','Herramienta para pruebas manuales de APIs.','https://www.postman.com/'],['↗','Chrome DevTools','Documentación oficial para investigar aplicaciones web.','https://developer.chrome.com/docs/devtools/'],['↗','Scrum Guide','Referencia oficial de Scrum.','https://scrumguides.org/scrum-guide.html?lang=es'],['↗','ISTQB CTFL','Referencia actual para fundamentos de Testing.','https://www.istqb.org/certifications/certified-tester-foundation-level']];return `<div class="page">${pageTitle('RECURSOS','Biblioteca de entrenamiento','Material de apoyo para estudiar y llevar la práctica fuera de la web.')}<div class="resource-grid">${rs.map(r=>`<a class="resource-card" href="${r[3]}" ${r[4]?'download':'target="_blank" rel="noreferrer"'}>${icon(r[0])}<div><h3>${esc(r[1])}</h3><p>${esc(r[2])}</p></div>${icon('›')}</a>`).join('')}</div><div class="callout">${icon('◇')}<div><h3>La práctica profesional vive fuera de esta app</h3><p>Moth Academy Web es tu herramienta de estudio y repaso. El proyecto práctico, los tickets y las entregas se trabajan con el instructor y el gestor de proyectos.</p></div></div></div>`}

function render(){let content={home,modules:modulesView,module:moduleView,practice:practiceView,interview:interviewView,journal:journalView,resources:resourcesView}[view]();document.getElementById('app').innerHTML=shell(content);bind();renderProgress()}
function bind(){document.querySelectorAll('[data-go]').forEach(el=>el.onclick=()=>go(el.dataset.go));document.querySelectorAll('[data-module]').forEach(el=>el.onclick=()=>openModule(Number(el.dataset.module)));document.querySelectorAll('[data-action="open-menu"]').forEach(el=>el.onclick=()=>{mobileOpen=true;render()});document.querySelectorAll('[data-action="close-menu"]').forEach(el=>el.onclick=()=>{mobileOpen=false;render()});document.querySelectorAll('[data-action="complete"]').forEach(el=>el.onclick=()=>toggleComplete(Number(el.dataset.id)));document.querySelectorAll('[data-practice]').forEach(el=>el.oninput=e=>{const [m,i]=el.dataset.practice.split('-');setPractice(m,i,e.target.value);el.nextElementSibling.textContent='Guardando...'});document.querySelectorAll('[data-interview]').forEach(el=>el.oninput=e=>setInterview(el.dataset.interview,e.target.value));document.querySelectorAll('[data-disclosure]').forEach(el=>el.onclick=()=>document.getElementById(`disc-${el.dataset.disclosure}`).classList.toggle('hidden'));const filter=document.getElementById('interview-filter');if(filter)filter.onchange=e=>{interviewFilter=e.target.value;interviewIndex=0;revealAnswer=false;render()};document.querySelectorAll('[data-action="reveal"]').forEach(el=>el.onclick=()=>{revealAnswer=!revealAnswer;render()});document.querySelectorAll('[data-action="next-question"]').forEach(el=>el.onclick=()=>{const list=interviewFilter==='all'?allInterviewQuestions:allInterviewQuestions.filter(q=>q.moduleId===Number(interviewFilter));interviewIndex=(interviewIndex+1)%list.length;revealAnswer=false;render()});document.querySelectorAll('[data-action="random"]').forEach(el=>el.onclick=()=>{const list=interviewFilter==='all'?allInterviewQuestions:allInterviewQuestions.filter(q=>q.moduleId===Number(interviewFilter));interviewIndex=Math.floor(Math.random()*list.length);revealAnswer=false;render()});document.querySelectorAll('[data-action="export"]').forEach(el=>el.onclick=exportProgress);document.querySelectorAll('[data-action="reset"]').forEach(el=>el.onclick=resetProgress);const imp=document.getElementById('import-progress');if(imp)imp.onchange=importProgress;const search=document.getElementById('module-search');if(search)search.oninput=e=>filterModules(e.target.value)}
function filterModules(q){const t=q.trim().toLowerCase();document.getElementById('module-grid').innerHTML=modules.filter(m=>!t||`${m.title} ${m.short} ${m.accent}`.toLowerCase().includes(t)).map(moduleCard).join('');document.querySelectorAll('#module-grid [data-module]').forEach(el=>el.onclick=()=>openModule(Number(el.dataset.module)))}
function exportProgress(){const blob=new Blob([JSON.stringify({...state,exportedAt:new Date().toISOString(),version:1},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`moth-academy-progreso-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url)}
function importProgress(e){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(r.result);state={...initialState,...p};delete state.exportedAt;delete state.version;saveState();render();flash('Progreso importado')}catch{alert('No pude leer ese archivo de progreso.')}};r.readAsText(f)}
function resetProgress(){if(!confirm('¿Querés borrar todo el progreso y las respuestas guardadas en este navegador?'))return;state={...initialState,completedModules:[],practiceAnswers:{},interviewAnswers:{}};saveState();render()}
render()
